import {StyleSheet, Platform} from 'react-native';

const styles = StyleSheet.create({
  container: {
    flexDirection: 'row',
    // paddingBottom: 12,
    // paddingBottom: dimensions.width * 0.033,
    // borderBottomWidth: 1,
    // borderBottomWidth: dimensions.width * 0.0027,
    borderColor: '#e0e0e0',
    height: 48,
    paddingHorizontal: 12,
    justifyContent: 'space-between',
    // height: imageHeight,
    // height: dimensions.width * 0.085,
    // position: 'relative',
    // width: '100%',
    // zIndex: 10,
    marginTop: 25,
    // position: 'absolute',
  },
  text: {
    fontFamily: 'Rubik',
    fontWeight: '400',
    color: '#B9B9B9',
  },
  selectedText:{
    color: 'black',
  },
  // options: {
  //   position: 'absolute',
  //   // zIndex: 1000,
  //   borderColor: '#EEF6FE',
  //   borderWidth: dimensions.width * 0.0027,
  //   // borderWidth: 1,
  //   // borderWidth: dimensions.width * 0.0027,
  //   // top: 30,
  //   top: dimensions.width * 0.152,
  //   // width: '100%',
  //   // flex: 1,
  //   // marginTop: -10,
  // },
  option: {
    fontSize: 14,
    fontFamily: 'Rubik',
    fontWeight: '400',
    padding: 10,
  },
  borderColor: {
    // borderBottomWidth: dimensions.width * 0.0027,
    borderColor: '#e0e0e0',
  },
  // containerBottomBorder: {
  //   flexDirection: 'row',
  //   // paddingBottom: 12,
  //   paddingBottom: dimensions.width * 0.033,
  //   // borderBottomWidth: 1,
  //   // borderBottomWidth: dimensions.width * 0.0027,
  //   borderColor: '#EEF6FE',
  //   // height: imageHeight,
  //   height: dimensions.width * 0.085,
  //   position: 'relative',
  //   // width: '100%',
  //   zIndex: 10,
  //   // justifyContent: 'space-between',
  //   // position: 'absolute',
  // },
  // containerIosBottomBorder: {
  //   flexDirection: 'row',
  //   // paddingBottom: 12,
  //   paddingBottom: dimensions.width * 0.033,
  //   // borderBottomWidth: 1,
  //   // borderBottomWidth: dimensions.width * 0.0027,
  //   borderColor: '#e0e0e0',
  //   // height: imageHeight,
  //   height: dimensions.width * 0.085,
  //   // position: 'relative',
  //   // width: '100%',
  //   //zIndex: 10,
  //   // justifyContent: 'space-between',
  // },
  // coloredText: {
  //   marginRight: dimensions.width * 0.022,
  //   // fontSize: 16,
  //   fontSize: dimensions.width * 0.033,
  //   fontWeight: '400',
  //   //marginLeft: dimensions.width * 0.063,
  //   color: 'red', //APP_COLORS.themeColor,
  //   marginLeft: 10,
  // },
});

export default styles;
