export default {
  magicMail: require('../assets/images/add-circle.png'),
  savePost: require('../assets/images/SavePost.png'),
  savePostFilled: require('../assets/images/bookmark.png'),
  delete: require('../assets/images/DeletIcon.png'),
  defaultImage: require('../assets/images/appProfilePic.png'),
  back: require('../assets/images/backarrow.png'),
  menu: require('../assets/images/menu.png'),
  referIcon: require('../assets/images/send.png'),
  placeholderImage: require('../assets/images/default.png'),
  groupIcon: require('../assets/images/group.png'),
  user: require('../assets/images/user.png'),
  add: require('../assets/images/plus.png'),
  next: require('../assets/images/next.png'),
  MyActivity: require('../assets/images/activity.png'),
  Approvalsimage: require('../assets/images/leaverequest.png'),
  leaverequestimage: require('../assets/images/profile2.png'),
  personalInfo: require('../assets/images/Personal.png'),
  policies: require('../assets/images/policies.png'),
  approval: require('../assets/images/user-tick.png'),
  tickets: require('../assets/images/receipt-2.png'),
  calendar: require('../assets/images/calendar.png'),
  logout: require('../assets/images/logout.png'),
  plusimage: require('../assets/images/pluswhite.png'),
  bluplusimage: require('../assets/images/plusimage2.png'),
  conference: require('../assets/images/CONFERENCEROOM.png'),
  Reimbursment: require('../assets/images/CONFERENCERE.png'),
  posh: require('../assets/images/POSH.png'),
  transport: require('../assets/images/TRANSPORT.png'),
  wfo: require('../assets/images/WORKFROMOFFICE.png'),
  lunch: require('../assets/images/TEAMLUNCH.png'),
  leave: require('../assets/images/LEAVEPOLICY.png'),
  // smartgig: require('../assets/images/smartgig.png'),
  // conference:require('../assets/images/conference.png'),
  // conference:require('../assets/images/conference.png'),
};
