import {StyleSheet} from 'react-native';
import {APP_COLOR} from '../../theme/color';
const styles = StyleSheet.create({
  HomeContentContainer: {
    backgroundColor: APP_COLOR.homebg,
    // flex: 1,
    borderTopLeftRadius: 36,
    borderTopRightRadius: 36,
    // padding: 20,
  },
  UseTimeContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingBottom: 0,
  },
  HolidayContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingBottom: 8,
  },
  Container: {
    height: 190,
    width: 160,
    padding: 8,
    backgroundColor: APP_COLOR.cards,
    borderRadius: 8,
    marginRight: 8,
    marginTop: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  name: {
    marginTop: 16,
    fontSize: 14,
    fontWeight: '600',
    color: APP_COLOR.text,
  },
  date: {
    marginTop: 2,
    fontSize: 10,
    //   fontWeight: '400',
    color: APP_COLOR.text,
  },
  newContainer: {
    backgroundColor: APP_COLOR.cards, // Replace with your color
    borderRadius: 8,
    paddingHorizontal: 20,
    paddingVertical: 12,
    width: 171,
    flexDirection: 'row',
    alignItems: 'center',
    height: 72,
    marginVertical: 8,
  },
  newContainer2: {
    backgroundColor: APP_COLOR.cards, // Replace with your color
    borderRadius: 8,
    paddingHorizontal: 20,
    paddingVertical: 12,
    width: 171,
    height: 72,
    marginVertical: 8,
  },
  popupContainer: {
    flex: 1,
    // backgroundColor: 'white',
    // // marginTop: '68%',
    // justifyContent: 'center',
    // alignItems: 'center',
    // height: '38%',
    // width: '70%',
    // paddingLeft: 10,
    // paddingRight: 10,
    // borderRadius: 15,
    // // borderWidth: 1,
    // // borderColor: '#0074B7',
    // // verticalAlign: 'center',
    // marginHorizontal: '15%',
  },
  popupText: {
    fontSize: 25,
    color: 'red',
    textAlign: 'center',
  },
  PersonName: {
    color: 'black',
    fontFamily: 'Pacifico-Regular',
    fontSize: 25,
    textAlign: 'center',
    // flex:1,
    // height:100,
    // width:
    // bottom:10,
    // paddingBottom:30,
    // marginHorizontal:60,
    // position: 'absolute',
    // marginVertical:5
  },
  container: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  orangeText: {
    color: 'orange',
  },
  blueText: {
    color: 'blue',
  },
  userName: {
    fontSize: 16,
    textAlign: 'center',
    color: '#202124',
    fontWeight: '500',
    // width: '100%',
    // position: 'absolute',
    // marginTop: 100,
    // width: 200,
  //  marginLeft:-15,
  },
  userName2:{
    fontSize: 16,
    textAlign: 'center',
    color: '#202124',
    fontWeight: '500',
    // position: 'absolute',
    // width: 200,
    // marginHorizontal:30,
    // marginTop:-10
  },
  HappyBirthday: {
    color: '#0074B7',
    fontSize: 34,
    fontWeight: '700',
    // marginVertical: 5,
    textAlign: 'center',
    fontFamily:'Montserrat',
    // paddingBottom: 10,
    // paddingLeft:20,
  },
  HappyBirthday2:{
    color: '#231F20',
    fontSize: 47,
    fontWeight: '400',
    // marginVertical: 5,
    // marginTop:-20,
    textAlign: 'center',
    fontFamily: 'Autography',
  },
  HappyAnniversary: {
    color: 'black',
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'center',
    width: '20%',
    // marginHorizontal:20
  },
  Happyanniversarys:{
    color: '#0074B7',
    fontSize: 34,
    fontWeight: '700',
    marginVertical: 5,
    textAlign: 'center',
    fontFamily:'Montserrat',
    // paddingBottom: 10,
    // paddingLeft:20,
  },
  Happyanniversary2:{
    color: '#231F20',
    fontSize: 35,
    fontWeight: '400',
    // marginTop:-20,
    textAlign: 'center',
    fontFamily: 'Autography',
    width:'100%',
    // marginHorizontal:7
  },
  happy: {
    alignSelf: 'center',
    color: 'black',
    fontSize: 18,
    fontWeight: 'bold',
  },
  mask: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
});
export default styles;
