// export const BIRTHDAYDATA = [
//   {
//     id: '1',
//     title: 'Skylar Korsgaard',
//     date: 'Mon, Jan 16 2023',
//     imageSource: require('../../assets/images/birthday.png'),
//   },
//   {
//     id: '2',
//     title: 'Peter Thornton',
//     date: 'Mon, Jan 16 2023',
//     imageSource: require('../../assets/images/birthday.png'),
//   },
//   {
//     id: '3',
//     title: 'Peter Thornton',
//     date: 'Mon, Jan 16 2023',
//     imageSource: require('../../assets/images/birthday.png'),
//   },
//   {
//     id: '4',
//     title: 'Sledge Hammer',
//     date: 'Mon, Jan 16 2023',
//     imageSource: require('../../assets/images/birthday.png'),
//   },
//   {
//     id: '5',
//     title: 'Willie Tanner',
//     date: 'Mon, Jan 16 2023',
//     imageSource: require('../../assets/images/birthday.png'),
//   },
//   {
//     id: '6',
//     title: 'Lynn Tanner',
//     date: 'Mon, Jan 16 2023',
//     imageSource: require('../../assets/images/birthday.png'),
//   },
//   {
//     id: '7',
//     title: 'Willie Tanner',
//     date: 'Mon, Jan 16 2023',
//     imageSource: require('../../assets/images/birthday.png'),
//   },
//   {
//     id: '8',
//     title: 'Angela Bower',
//     date: 'Mon, Jan 16 2023',
//     imageSource: require('../../assets/images/birthday.png'),
//   },
//   {
//     id: '9',
//     title: 'Michael Knight',
//     date: 'Mon, Jan 16 2023',
//     imageSource: require('../../assets/images/birthday.png'),
//   },
//   {
//     id: '10',
//     title: 'Col. Roderick Decker',
//     date: 'Mon, Jan 16 2023',
//     imageSource: require('../../assets/images/birthday.png'),
//   },
//   {
//     id: '11',
//     title: 'Tony Danza',
//     date: 'Mon, Jan 16 2023',
//     imageSource: require('../../assets/images/birthday.png'),
//   },
//   {
//     id: '12',
//     title: 'Tony Danza',
//     date: 'Mon, Jan 16 2023',
//     imageSource: require('../../assets/images/birthday.png'),
//   },
//   {
//     id: '13',
//     title: 'Willie Tanner',
//     date: 'Mon, Jan 16 2023',
//     imageSource: require('../../assets/images/birthday.png'),
//   },
//   {
//     id: '14',
//     title: 'Tony Danza',
//     date: 'Mon, Jan 16 2023',
//     imageSource: require('../../assets/images/birthday.png'),
//   },
//   {
//     id: '15',
//     title: 'Tony Danza',
//     date: 'Mon, Jan 16 2023',
//     imageSource: require('../../assets/images/birthday.png'),
//   },
// ];
// export const ANNIVERSARYDATA = [
//   {
//     id: '1',
//     title: 'Skylar Korsgaard',
//     date: 'Mon, Jan 16 2023',
//     imageSource: require('../../assets/images/birthday.png'),
//     imageSources: require('../../assets/images/rectangle.png'),
//     number: '1',
//   },
//   {
//     id: '2',
//     title: 'Peter Thornton',
//     date: 'Mon, Jan 16 2023',
//     imageSource: require('../../assets/images/birthday.png'),
//     imageSources: require('../../assets/images/rectangle.png'),
//     number: '2',
//   },
//   {
//     id: '3',
//     title: 'Peter Thornton',
//     date: 'Mon, Jan 16 2023',
//     imageSource: require('../../assets/images/birthday.png'),
//     imageSources: require('../../assets/images/rectangle.png'),
//     number: '3',
//   },
//   {
//     id: '4',
//     title: 'Sledge Hammer',
//     date: 'Mon, Jan 16 2023',
//     imageSource: require('../../assets/images/birthday.png'),
//     imageSources: require('../../assets/images/rectangle.png'),
//     number: '4',
//   },
//   {
//     id: '5',
//     title: 'Willie Tanner',
//     date: 'Mon, Jan 16 2023',
//     imageSource: require('../../assets/images/birthday.png'),
//     imageSources: require('../../assets/images/rectangle.png'),
//     number: '5',
//   },
//   {
//     id: '6',
//     title: 'Lynn Tanner',
//     date: 'Mon, Jan 16 2023',
//     imageSource: require('../../assets/images/birthday.png'),
//     imageSources: require('../../assets/images/rectangle.png'),
//     number: '6',
//   },
//   {
//     id: '7',
//     title: 'Willie Tanner',
//     date: 'Mon, Jan 16 2023',
//     imageSource: require('../../assets/images/birthday.png'),
//     imageSources: require('../../assets/images/rectangle.png'),
//     number: '7',
//   },
//   {
//     id: '8',
//     title: 'Angela Bower',
//     date: 'Mon, Jan 16 2023',
//     imageSource: require('../../assets/images/birthday.png'),
//     imageSources: require('../../assets/images/rectangle.png'),
//     number: '8',
//   },
//   {
//     id: '9',
//     title: 'Michael Knight',
//     date: 'Mon, Jan 16 2023',
//     imageSource: require('../../assets/images/birthday.png'),
//     imageSources: require('../../assets/images/rectangle.png'),
//     number: '9',
//   },
//   {
//     id: '10',
//     title: 'Col. Roderick Decker',
//     date: 'Mon, Jan 16 2023',
//     imageSource: require('../../assets/images/birthday.png'),
//     imageSources: require('../../assets/images/rectangle.png'),
//     number: '10',
//   },
//   // {
//   //   id: '11',
//   //   title: 'Tony Danza',
//   //   date: 'Mon, Jan 16 2023',
//   //  imageSource: require('../../assets/images/birthday.png'),
//   //   number: '11',
//   // },
//   {
//     id: '11',
//     title: 'Tony Danza',
//     date: 'Mon, Jan 16 2023',
//     imageSource: require('../../assets/images/birthday.png'),
//     imageSources: require('../../assets/images/rectangle.png'),
//     number: '11',
//   },
//   {
//     id: '12',
//     title: 'Willie Tanner',
//     date: 'Mon, Jan 16 2023',
//     imageSource: require('../../assets/images/birthday.png'),
//     imageSources: require('../../assets/images/rectangle.png'),
//     number: '12',
//   },
//   {
//     id: '13',
//     title: 'Tony Danza',
//     date: 'Mon, Jan 16 2023',
//     imageSource: require('../../assets/images/birthday.png'),
//     imageSources: require('../../assets/images/rectangle.png'),
//     number: '13',
//   },
//   {
//     id: '14',
//     title: 'Tony Danza',
//     date: 'Mon, Jan 16 2023',
//     imageSource: require('../../assets/images/birthday.png'),
//     imageSources: require('../../assets/images/rectangle.png'),
//     number: '14',
//   },
// ];
